### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by NPException** [NPException42/Dimensional-Pockets#2]
- [x] **Exiting the cell**
- **Persisting the TeleportingRegistry**
  - [x] persist the soon-to-exist Pocket map
  - [x] persist _currentChunk_
- [x] **Portal code**
  - Changing this to teleport you to a very specific spot.
  - I'll also make sure you can change this.
- [x] **Textures**
  - textures for ender crystal and nether crystal
- [x] **Smoother gen for the dimension**
- [x] **Book thingy**, for information on how to use the mod.
  - Make it a quick intro guide to the mod, how it works, etc.
  - make the book appear in the players inventory on first login
- [x] **Chunk Loading**
  - We need to load the chunks that have been gen'd.
  - note to self (NPE): https://github.com/iChun/Sync/search?q=ChunkLoadHandler&ref=cmdform
  - Chunks are loaded. Need to look more into this.
- [x] ~~**Redstone Compatablity**~~
  - ~~NPE or Nox, good luck, should be fairly easy.~~
  - ~~Use the tileEntity as a bridge for the block method that detects if there is a change.~~
- [x] **Particles**
  - NPE or Myself, we discussed this...
  - Particles going into the block.
  - Particles leaving the block from the player, as an explosion.
- [x] **Recipes**
  - Speaks for itself again.
- [x] **The Lights** (very low priority)
  - The blocks are supposed to have light given the light from the world.
  - right now they just emit the maximum possible amount of light
- [x] ~~**Hopefully, all these are done**~~
  - ~~Once all the above are done, and we have enough time, see if we can add support for other mods, etc.~~
